#!/usr/bin/env python2.7
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, version 1.1 (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at ./LICENSE.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at ./LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

# Copyright (c) 2015 Daniel W. Steinbrook. All rights reserved.

import sys
import argparse

from libzzzfs import zpool
from libzzzfs.dataset import ZzzFSException
from libzzzfs.util import PropertyList


if __name__ == '__main__':
    parser = argparse.ArgumentParser(add_help=False)
    subparsers = parser.add_subparsers(dest='command', title='subcommands')

    # per-command arguments
    create = subparsers.add_parser('create')
    create.add_argument('pool_name')
    create.add_argument('disk')

    destroy = subparsers.add_parser('destroy')
    destroy.add_argument('pool_name')

    list = subparsers.add_parser('list')
    list.add_argument('pool_name', nargs='?', default=None)
    list.add_argument('-H', action='store_true', dest='scriptable_mode')
    list.add_argument(
        '-o', metavar='property[,...]', type=PropertyList, dest='headers',
        default=PropertyList('name,size,alloc,free,cap,health,altroot'))

    # generate dict of argument keys/values
    args = parser.parse_args()
    params = dict(args._get_kwargs())
    del params['command']

    try:
        output = getattr(zpool, args.command)(**params)
    except ZzzFSException, e:
        sys.exit('%s: %s' % (sys.argv[0], e))

    if output:
        print output
